# Generated by Django 5.1 on 2024-09-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_registration',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
