# Generated by Django 3.2 on 2024-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
