# Generated by Django 3.2 on 2024-09-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240925_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
