# Generated by Django 3.2 on 2024-09-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20240926_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='online_consultation',
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Both', 'Both')], default='Offline', max_length=20),
        ),
    ]
