# Generated by Django 3.2 on 2024-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240926_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinic_address',
            field=models.TextField(null=True),
        ),
    ]
